import PagesContainer from "./containers/pagesContainer";
import UrgeWithPleasureComponent from "./UrgeWithPleasureComponent";
import Table from "./table";
import Title from "./title";
import TableRegu from "./tableRegu";
import TableDetailRegu from "./tableDetailRegu";
import Pangkalan from "../pages/pangkalan";
import TablePangkalan from "./tablePangkalan";
import TablePangkalanDetail from "./tablePangkalanDetail";
import TableLomPangkalan from "./tableLomPangkalan";
export { PagesContainer, UrgeWithPleasureComponent, Table, Title, TableRegu, TableDetailRegu, Pangkalan, TablePangkalan, TablePangkalanDetail, TableLomPangkalan };